name: ClaudeModelSwitcher
options:
  bundleIdPrefix: com.claudemodelswitcher
  deploymentTarget:
    macOS: "14.0"

settings:
  base:
    PRODUCT_NAME: Claude Model Switcher
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    PRODUCT_BUNDLE_IDENTIFIER: com.claudemodelswitcher.app

targets:
  ClaudeModelSwitcher:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: ClaudeModelSwitcher.entitlements
        LSUIElement: NO
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025. All rights reserved."
    entitlements:
      path: ClaudeModelSwitcher.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.files.user-selected.read-write: true
